import Head from 'next/head';
import Header from '../components/Header';
// import Image from 'next/image';

export default function Home() {
  return (
    <div className='flex flex-col items-center justify-center min-h-screen py-2'>
      <Head>
        <title>Pountzas</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
      <h1>Start</h1>
    </div>
  );
}
