import Head from "next/head";
import HomeAnimations from "../components/animations/HomeAnimations";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pountzas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/faviconnikos.ico" />
      </Head>

      <HomeAnimations />
    </>
  );
}
