import Head from 'next/head';
import Header from '../components/Header';
import Socials from '../components/Socials';
import Link from 'next/link';
// import Image from 'next/image';

export default function Home() {
  return (
    <div className='bg-gray-700 min-h-screen'>
      <Head>
        <title>Pountzas</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
      <div className='pt-8 mt-16 border border-blue-200 rounded-lg bg-gray-900 space-y-5 grid-cols-1 max-w-lg md:max-w-4xl xl:max-w-6xl mx-auto'>
        <div className='text-xl text-blue-200 font-semibold px-5 mb-8 text-center space-y-10'>
          <h1 className='text-center'>Hello I am Nikos.</h1>
          <h2>I am a full-stack web developer</h2>
          <p>
            I am from Greece and i have studied Graphic Design and Web
            Development.
          </p>
          <p className=''>I specialize in JavaScript, React and NEXT.js</p>
        </div>
        <div>
          <h3 className='text-center text-blue-200'>My Social Network</h3>
          <div className='flex items-center justify-center space-x-3 py-2 md:py-5'>
            {Socials.map((social) => (
              <div
                className='text-blue-200 hover:text-blue-50 pb-3'
                key={social.id}
              >
                <Link href={social.path} passHref>
                  <a className='text-3xl md:text-6xl' target='_blank'>
                    {social.icon}
                  </a>
                </Link>
              </div>
            ))}
          </div>
          <div className='flex items-center justify-center pb-8'>
            <Link
              className=''
              href='https://drive.google.com/file/d/10t7ZsxaEFjPltG3Fi9fRVgIfT2jbygci/view?usp=sharing'
              passHref
            >
              <a
                target='_blank'
                className='p-2 rounded-lg cursor-pointer text-center text-blue-200 hover:text-blue-50 font-semibold border-2 border-blue-200 bg-gray-800'
              >
                My CV
              </a>
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
